import { Router, type IRouter } from "express";
import { aiLimiter } from "../middlewares/rateLimiter";
import healthRouter from "./health";
import ownersRouter from "./owners";
import patientsRouter from "./patients";
import consultationsRouter from "./consultations";
import actesRouter from "./actes";
import facturesRouter from "./factures";
import aiRouter from "./ai";
import dashboardRouter from "./dashboard";
import storageRouter from "./storage";
import rappelsRouter from "./rappels";
import vaccinationsRouter from "./vaccinations";
import stockRouter from "./stock";
import rendezVousRouter from "./rendez-vous";
import anesthesieRouter from "./anesthesie";
import portailRouter from "./portail";
import statistiquesRouter from "./statistiques";
import ordonnancesRouter from "./ordonnances";
import parametresCliniqueRouter from "./parametres-clinique";
import agendaRouter from "./agenda";
import searchRouter from "./search";
import encaissementsRouter from "./encaissements";
import vetKnowledgeRouter from "./vet-knowledge";
import equipeRouter from "./equipe";
import ventesRouter from "./ventes";
import adminPermissionsRouter from "./admin/permissions";
import adminAiCostsRouter from "./admin/ai-costs";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/owners", ownersRouter);
router.use("/patients", patientsRouter);
router.use("/consultations", consultationsRouter);
router.use("/actes", actesRouter);
router.use("/factures", facturesRouter);
router.use("/ai", aiLimiter, aiRouter);
router.use("/dashboard", dashboardRouter);
router.use("/rappels", rappelsRouter);
router.use("/vaccinations", vaccinationsRouter);
router.use("/stock", stockRouter);
router.use("/rendez-vous", rendezVousRouter);
router.use("/anesthesie", anesthesieRouter);
router.use("/statistiques", statistiquesRouter);
router.use("/portail", portailRouter);
router.use("/ordonnances", ordonnancesRouter);
router.use("/parametres-clinique", parametresCliniqueRouter);
router.use("/agenda", agendaRouter);
router.use("/search", searchRouter);
router.use("/encaissements", encaissementsRouter);
router.use("/vet-knowledge", vetKnowledgeRouter);
router.use(storageRouter);
router.use("/equipe", equipeRouter);
router.use("/ventes", ventesRouter);
router.use("/admin/permissions", adminPermissionsRouter);
router.use("/admin", adminAiCostsRouter);

import cremationRouter from "./cremation";
router.use("/cremation-partners", cremationRouter);

export default router;
